force-app/main/default/objects/Quote/fields/Quotient_Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Quotient_Quote_Number__c</fullName>
    <label>Quotient Quote Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Total_Price_Including_Tax__c.field-meta.xml
<CustomField>
    <fullName>Total_Price_Including_Tax__c</fullName>
    <label>Total Price Including Tax</label>
    <summarizedField>QuoteLineItem.Total_Price_Including_Tax__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/CustomQuoteRelatedListController.cls
public with sharing class CustomQuoteRelatedListController {

    @AuraEnabled(cacheable=true)
    public static List<Quote> getQuotes(Id parentId) {
        return [
            SELECT Id,
                   Name,
                   Quotient_Quote_Number__c,
                   TotalPrice,
                   Total_Price_Including_Tax__c,
                   AccountId,
                   OpportunityId, Status
            FROM Quote
            WHERE AccountId = :parentId
               OR OpportunityId = :parentId
            ORDER BY CreatedDate DESC
        ];
    }
}